### ISSUE TITLE
Compatibilidade com Windows 7

### ISSUE THREAD

**Issue by RafaelMCarvalho** [pagseguromaster/plugpag#1]
Desenvolvemos em minha empresa um app Windows em Python utilizando o PlugPag. Está funcionando com Windows 10 e 8, mas com o Windows 7 a lib simplesmente não consegue fazer as chamadas ao POS, como se não tivessem dispositivos em porta COM alguma. 

Alguém sabe me dizer se:

1. A lib PlugPlag é compatível com Windows 7?
2. Precisa fazer algo diferente na integração pra funcionar com o Windows 7?
3. A Moderninha PRO é compatível com Windows 7?
4. Existe algum app demo funcional para o Windows 7?

Obrigado!

**Comment by hhideki** [comment]
Rafael, as versões homologadas são as seguintes:
- Windows 7 32 bit: OK
- Windows 7 64 bit: OK
- Windows 8 64 bit: OK
- Windows 10 64 bit: OK

As versões não homologadas:
- Windows XP 32/64 bit: Não há mais suporte da Microsoft desde 2014
- Windows Vista 32/64 bit: Não há mais suporte da Microsoft desde março de 2017
- Versões anteriores ao Windows XP

Os testes foram feitos utilizando dongles bluetooth 2.0 e 4.0, utilizando as aplicações de demonstração em Python e em Java presentes nesse repositório.

**Comment by RafaelMCarvalho** [comment]
Olá, Hugo. Obrigado pela resposta.

Não tivemos sucesso no Windows 7 com o dongle 2.0 que temos aqui, mas a qualidade parecia péssima. Sequer tem marca.

Com o 2.1 do próprio notebook LG P430 também não funcionou.

Por fim, com o 4.0 da marca ORICO, modelo BTA-403-BK, funcionou. 

Estávamos utilizando a Moderninha PRO (PAX P920).

Seria interessante se vocês pudessem ter uma lista de marcas e modelos de dongles testados, além da versão do bluetooth em si. Se puderem incluir em algum README.md ou no Wiki aqui do GitHub mesmo seria ótimo.

Estou à disposição se precisarem de mais informações.
