### ISSUE TITLE
Configurar minizinha chip para rodar nova versão da API

### ISSUE THREAD

**Issue by backsubzero** [pagseguromaster/plugpag#10]
Tentei parear ela, porem não aparece como dispositivo bluetooth, usando o metodo das anteriores não funciona.
Versão APP 1.0.9
Versão SO 01.01
Versão EMV v605

mandei atualizar e está na ultima versão disponível.
como proceder ?

**Comment by henriquealrs** [comment]
Olá.

A Minizinha Chip deve estar na versão de sofware 1.10 (o changelog já foi corrigido)

Se quiser pode passar o Número de Série da sua Minizinha Chip para que possamos programar a atualização. A versão entratá em rollout em breve, também, então a atualização ocorrerá automaticamente.

Obrigado

**Comment by backsubzero** [comment]
SN 1220194332 - Obrigado

**Comment by henriquealrs** [comment]
Boa tarde, a atualização já foi agendada.

Vou fechar o issue.
Obrigado

**Comment by backsubzero** [comment]
sim, já consegui parear, inclusive testei parear com o raspberry e deu certo.
Obrigado.

**Comment by jg19** [comment]
Minizinha Chip não está aparecendo no aplicativo Vendas do Pagseguro.
E não é identificada como leitor por nenhum dos 2 aplicativos de demonstração. Tenho uma Mini que aparece em todos os aplicativos, mas a Minizinha Chip não é identificada como leitor.
O pareamento ocorre normalmente em ambas as maquinas, apenas a Minizinha Chip não aparece.
