### ISSUE TITLE
Moderninha wifi - procedimento para parear

### ISSUE THREAD

**Issue by backsubzero** [pagseguromaster/plugpag#14]
Estou com uma moderninha wifi que não consigo ligar o bluetooth para parear, atualizei e nada.
versão 03.17.01.002
Como devo proceder ?

**Comment by hhideki** [comment]
Para esse tipo de dúvida, favor entrar em contato com a central de atendimento.
https://faq.pagseguro.uol.com.br/ligue-central-atendimento
