### ISSUE TITLE
Autenticação com PagSeguro indica sem internet em tablet Samsung.

### ISSUE THREAD

**Issue by joaogalli** [pagseguromaster/plugpag#16]
Estou utilizando aplicativo "simple-demo" em vários dispositivos com sucesso, mas tenho um tablet Samsung Tab S 1 que apresenta uma mensagem de falta de internet quando tento fazer login.

Seria algo específico da Samsung?

Versão do Android: 6.0.1

**Comment by backsubzero** [comment]
> Estou utilizando aplicativo "simple-demo" em vários dispositivos com sucesso, mas tenho um tablet Samsung Tab S 1 que apresenta uma mensagem de falta de internet quando tento fazer login.
> 
> Seria algo específico da Samsung?
> 
> Versão do Android: 6.0.1

Já tentou atualizar o tablet ou testar em algum outro como huawei, Alcatel, etc,  com android puro ou com versão superior como 7.x ? porque pelo que eu me lembro o TLS não opera legal no Android da samsung...

**Comment by joaogalli** [comment]
Sim, já testei em outros, até em versões mais antigas do Android (5) puro e funcionou.
Entendo que a Samsung modifica mais o Android que as outras, mas por que o login do aplicativo oficial do PagSeguro Vendas funciona no mesmo tablet?

**Comment by backsubzero** [comment]
> Sim, já testei em outros, até em versões mais antigas do Android (5) puro e funcionou.
> Entendo que a Samsung modifica mais o Android que as outras, mas por que o login do aplicativo oficial do PagSeguro Vendas funciona no mesmo tablet?

Provavelmente o APP deve levar alguma lib a mais com ele, só eles que vão poder dizer a diferença... mais para aplicações em outra área tive tantos problemas com samsung devido as mudanças que eles fazem que eu coloco como incompatível com samsung "tablets e celulares" cada aparelho eu tinha um problema diferente, acabei desistindo... mais me lembro bem que TLS era um problema enorme nele.

**Comment by joaogalli** [comment]
Poderia ser o fato de o aplicativo (PagSeguro Vendas) estar assinado ou na Play Store?

**Comment by backsubzero** [comment]
Duvido muito, no meu caso eram apps para uso medico, só dava problema em samsung, nos demais funcionam de primeira, nunca coloquei na Play Store, mesmo porque precisa configurar toda parte de servidor...

**Comment by hhideki** [comment]
@joaogalli, complementando o que o @backsubzero falou, houve uma alteração de segurança que força todas as conexões a utilizarem TLS 1.2.

Eu vi que o Samsung Galaxy Tab S possui alguns modelos diferentes, dependendo do tamanho da tela. Você pode me informar qual é o modelo do seu tablet, por favor?

Teoricamente, para Android 4.1 ao 5.0 (considerando apenas smartphones), há suporte para TLS 1.2 (mas a fabricante pode remover ou desabilitar), mas não vem habilitado. Para Android 5.0 em diante, TLS 1.2 vem habilitado. Considerando que a Samsung não altere nada referente a essa parte, o seu tablet deveria funcionar normalmente com o PlugPag.

A mensagem de erro informando falta de conexão com a internet é exibida sempre que não há conexão com a internet ou ocorre uma falha de comunicação com nossos servidores. Uma das falhas pode ser a falha de comunicação devido ao protocolo TLS 1.2.

Eu vou tentar analisar o problema e aplicar uma correção para forçar o TLS 1.2 nessa versão (da mesma forma que o PagSeguro Vendas faz).

**Comment by joaogalli** [comment]
@hhideki obrigado,
O meu tablet é um Galaxy Tab S 1, de 8,4".
Ele está com Android 6.0.1

Funcionou em:
Nexus 4 com Android 5
Moto Z1 Play com Android 8

**Comment by joaogalli** [comment]
Identificamos mais um aparelho com o problema: Multilaser M7s plus.

**Comment by lucamenor** [comment]
Olá, estou trabalhando em uma integração com a PlugPag e passei por esse mesmo problema de indicar que não tem internet, quando na verdade tem.

Pelo que pude debugar e analisar, o problema acontece quando o dispositivo não tem um registro de IMEI. A classe de autenticação da PlugPag utiliza o IMEI para alguma coisa (é uma chamada native, por isso não consegui analisar diretamente), e quando ele é NULL (caso do tablet samsung e outros tablets sem entrada para chip SIM), essa lógica de autenticação sempre retorna NULL, fazendo com que a mensagem de sem internet seja exibida.

Não sei qual uso vocês fazem do IMEI, mas a lógica deveria ser alterada para esperar o valor NULL também ou usar outra forma de identificar o hardware. Isso impossibilita a integração com vários dispositivos que não tem chip SIM (tablets, totens, hardwares personalizados), fechando o uso para celulares e tablets com chip.

Vocês poderiam analisar e dar algum retorno sobre essa questão? Esse problema está afetando diretamente uma solução conjunta de hardware e software que estamos desenvolvendo.

**Comment by joaogalli** [comment]
Devo admitir que pensava que para integrar a maquininha com o aplicativo era necessário logar no PagSeguro, acabei removendo o login. Agora só faço o pareamento bluetooth e envio os comandos para a maquininha.

**Comment by lucamenor** [comment]
@joaogalli Você está fazendo os pagamentos sem fazer a autenticação? E como os pagamentos estão sendo creditados na conta correta do PagSeguro?

**Comment by joaogalli** [comment]
@lucamenor o meu fluxo é o seguinte: com a venda pronta no aplicativo, mando um comando para a maquininha pareada e ela faz o pagamento, pois ela está registrada/logada no PagSeguro, então eu só preciso mandar comando para ela e receber a resposta dela se deu certo ou errado.

**Comment by lucamenor** [comment]
@joaogalli Entendi. Não sabia que podia fazer isso. Então pra que serve a autenticação? Eu imaginava que a autenticação é quem faria a associação da venda com a conta correta do PagSeguro.

**Comment by joaogalli** [comment]
@lucamenor acredito que a autenticação permita que você faça consultas e até pagamento pelo app sem ter a maquininha. Não sei se essa API faz tudo isso, mas existe essa possibilidade.
Por exemplo, é interessante poder estornar um pagamento pelo APP ao invés da maquininha.

**Comment by lucamenor** [comment]
@hhideki Você pode confirmar o uso e a necessidade da autenticação? Tentei encontrar algum ponto da documentação que fale sobre isso, mas não tem.

@joaogalli Entendi seu ponto de vista. Vou tentar fazer algum teste nesse sentido, enquanto não temos uma resposta oficial da PagSeguro.

**Comment by backsubzero** [comment]
Se for a minizinha chip não precisa mesmo, só mandar os comandos para a maquina, porque ela é quem faz o processo de registro e tal, a minizinha chip é autonoma.

já a minizinha sem chip, precisa sim da autenticação.

**Comment by joaogalli** [comment]
@backsubzero estou usando a moderninha plus com chip. Creio que entra nessa também.
A minizinha chip eu não consigo pareamento nem com o app do PagSeguro Vendas.

O que você quer dizer então, é que se eu tenho uma maquininha **sem** chip da PagSeguro, ela é só um leitor de cartão com um teclado para o usuário digitar a senha? O meu app precisa fazer todo o resto?

**Comment by lucamenor** [comment]
@backsubzero a que temos aqui é a minizinha sem chip, por conta do fluxo da aplicação. Você trabalha na PagSeguro? Essa questão de autenticação nos dispositivos sem IMEI está bloqueando nosso desenvolvimento. Gostaríamos de algum feedback sobre isso. Se tem algum contorno, se será lançada alguma correção sobre isso, etc.

**Comment by backsubzero** [comment]
@joaogalli exato, maquina sem chip o APP faz tudo, maquina com chip vc só manda que ela executa.
@lucamenor não trabalho na pagseguro, tenho um projeto que estou migrando para o pagseguro em raspberry com totens de auto-atendimento, e vamos usar minizinha-chip exatamente para não precisar cuidar desta parte de trafego e autenticação.

sobre a questão do IMEI, no meu ponto de vista é segurança, vc precisa de dispositivos que tenham isso, se o seu fluxo precisa de maquinas sem chip, é uma premissa de segurança amarrar o IMEI para confirmar de onde saiu o pedido do pagamento.
Em questão de pagamentos, todo cuidado é pouco, então se eu estivesse no core do pagseguro eu até bloquearia dispositivos não homologados na anatel para evitar problemas...

Por isso vejo a moderninha wifi / minizinha chip como melhores opções para desenvolvimento, deixa toda parte de segurança com eles e sem riscos para nós e para eles...

**Comment by brunonmelo** [comment]
@backsubzero, eu tenho que discordar de você no ponto em que o IMEI é um requerimento pra garantir de onde vem a transação. 
Qualquer aparelho pode ter seu IMEI burlado ou modificado. Cada transação tem um um usuário vinculado e pode ser capturado o IP de origem também.
Querer vetar o uso do serviço por causa do device ser homologado ou não ou ter IMEI ou não. não é responsabilidade da pagseguro. A obrigação deles é garantir o fluxo da transação, e mesmo que seja uma forma de garantir a segurança, tem outro meios ou dados que da para recolher que não restrinja o tipo de device que pode utiliza-lo.

**Comment by joaogalli** [comment]
@backsubzero , só uma adição aí, máquina com WIFI também funciona independente. Acabei de testar com a Moderninha Plus no Wifi apenas.

**Comment by backsubzero** [comment]
@joaogalli sim, a moderninha pro tbm funciona normal, wifi e GPRS

**Comment by backsubzero** [comment]
> @backsubzero, eu tenho que discordar de você no ponto em que o IMEI é um requerimento pra garantir de onde vem a transação.
> Qualquer aparelho pode ter seu IMEI burlado ou modificado. Cada transação tem um um usuário vinculado e pode ser capturado o IP de origem também.

ok, concordo, porem o fato de ser mais uma proteção, quanto mais formas tiverem melhor, isso vc concorda ?

> Querer vetar o uso do serviço por causa do device ser homologado ou não ou ter IMEI ou não. não é responsabilidade da pagseguro. A obrigação deles é garantir o fluxo da transação, e mesmo que seja uma forma de garantir a segurança, tem outro meios ou dados que da para recolher que não restrinja o tipo de device que pode utiliza-lo.

Vetar equipamentos não homologados é obedecer a legislação em vigor, é só uma proteção a mais, como a anterior, eles possuem PCI compliance, para atender isso existem diversas regras que eles cumprem para conseguir o selo, eu sou paranoico por segurança, colocaria tudo que tivesse ao meu alcance, não existe o infalível e vc sabe, se está na internet está vulnerável, mais prefiro pecar por exagero do que por falta. 

PS: IMEI parece ser parte do PCI para dispositivos de pagamento móvel, faz anos que eu larguei isso porem lembro de ter visto algo.

**Comment by joaogalli** [comment]
Agradeço o apoio de todos, acredito que ficou resolvido com essa questão do IMEI.

**Comment by lucamenor** [comment]
Apenas adicionando uma observação para o interesse de todos. A PagSeguro liberou uma nova versão da API que corrige esse problema do IMEI null em alguns devices. Quando não existir IMEI ela vai buscar o SECURE ID do device. Dessa forma a API agora pode ser utilizada em tablets sem entrada para chip SIM.
