### ISSUE TITLE
Desfazimento da transação

### ISSUE THREAD

**Issue by brunonmelo** [pagseguromaster/plugpag#19]
Bom dia,
Eu estou usando a biblioteca PlugPag, e por uma regra de negocio, precisamos limitar as bandeiras dos cartões que serão aceitos. No entanto eu não vi nada parecido com essa opção na documentação, então pensei em realizar o desfazimento da transação caso a bandeira não seja a correspondente com as que a gente irá aceitar, mas não encontrei essa opção também.

Existe alguma opção ou funcionalidade de desfazimento ou confirmação da transação?
E se for o caso, qual o ponto da documentação estaria essa implementação?

Ou, de que outra forma eu poderia realizar essa limitação de bandeiras de cartões aceita?

**Comment by hhideki** [comment]
@brunonmelo

> Eu estou usando a biblioteca PlugPag, e por uma regra de negocio, precisamos limitar as bandeiras dos cartões que serão aceitos.

Não é possível controlar as bandeiras que são aceitas. Todos os terminais aceitam as mesmas bandeiras.

> Existe alguma opção ou funcionalidade de desfazimento ou confirmação da transação?

Se ocorreu algum erro durante a transação e houve necessidade de fazer um desfazimento, nossa biblioteca já controla isso. Se a biblioteca retornou RET_OK para a transação, então a transação foi realizada com sucesso. Se a biblioteca retornou algum erro, então o desfazimento já será feito automaticamente se for necessário.

> Ou, de que outra forma eu poderia realizar essa limitação de bandeiras de cartões aceita?

Vou confirmar com alguém da área de negócios, mas creio que não seja possível limitar as bandeiras.

**Comment by brunonmelo** [comment]
@hhideki tudo bem. Agradeço.

**Comment by hhideki** [comment]
@brunonmelo, confirmei e realmente não há como limitar as bandeiras aceitas.
