### ISSUE TITLE
Não é possível recuperar informações da transação

### ISSUE THREAD

**Issue by FilipeLipan** [pagseguromaster/plugpag#26]
existe alguma forma de recuperar o Id da transação?
e também ter acesso a via do cliente?

PlugPagTransactionResult.transactionId retorna null, ele é um valor que o cliente seta?

**Comment by hhideki** [comment]
@FilipeLipan, o identificador da transação deve ser retornado no PlugPagTransactionResult.
Não é toda transação que possui o transactionId, mas o transactionCode deve existir.
Quando houver transactionId, a transação é identificada pelo par <transactionCode, transactionId>. Quando não houver o transactionId, a transação é identificada apenas pelo transactionCode.

Não há como obter a via do cliente ou a via do estabelecimento.
As vias do comprovante são documentos impressos apenas uma vez (todas as demais impressões são REIMPRESSÕES).
