### ISSUE TITLE
Documentação não informa o tipo de "calling convention" das bibliotecas para Windows

### ISSUE THREAD

**Issue by silvioprog** [pagseguromaster/plugpag#4]
Boa tarde.

Gostaria de saber qual o tipo de "calling convention" (**cdecl** ou **stdcall**) utilizado pelas bibliotecas para Windows. Estou criando um binding para Delphi e o compilador requer esta definição, assim a classe wrapper conseguirá parametrizar as funções corretamente.

Obrigado!

**Comment by silvioprog** [comment]
Descobri aqui, é **stdcall**. :smiley:

**Comment by danilogrespan** [comment]
> Descobri aqui, é **stdcall**. Meu componente Delphi para usar PlugPag via USB/Bluetooth está funcionando lindamente bem! \o/

Caramba, consegue dizer como montou? Não manjo nada de Java mas sim de Delphi

**Comment by backsubzero** [comment]
Eu tinha desistido por falta de suporte...

Como você conseguiu fazer funcionar no delphi ? eu tenho até a 10.3 aqui, é
compatível ? parei de pagar a atualização do delphi porque a operação parou
na pandemia e não valia mais renovar para não fazer nada comercial...


sds
Marcelino Viana Pinheiro
+55 41 999113586 TIM
+55 41 984188001 VIVO
+55 41 992368001 VIVO (Signal e Whatsapp)
backsubzero (Skype)
@BackSubZero (Telegram)


Em ter., 30 de jan. de 2024 às 19:50, danilogrespan <
***@***.***> escreveu:
