### ISSUE TITLE
Impossibilidade de voucher com a Minizinha

### ISSUE THREAD

**Issue by oliveira-marcello** [pagseguromaster/plugpag#6]
Olá, estou usando a versão 3.0.0 do PlugPag no Android, e está funcionando perfeitamente para pagar por débito e crédito na Minizinha. Porém quando tento fazer um pagamento por voucher, o método doPayment já retorna rapidamente um PlugPagTransactionResult que tem resultado PlugPag.RET_OK, sem que a Minizinha peça para inserir o cartão ou digitar a senha.

**Comment by hhideki** [comment]
Encontramos um erro no código.
Já fizemos a correção e estará disponível no próximo release.

**Comment by hhideki** [comment]
@oliveira-marcello, a versão 3.0.1 foi liberada para Android e deve corrigir esse problema.
Uma melhoria no retorno das transações foi implementada. Por favor, aproveite para verificar se seu código continua compilando e rodando.

Espero ter ajudado nesse problema.

**Comment by oliveira-marcello** [comment]
Obrigado @hhideki, testei com a nova versão e agora o voucher está funcionando.
