### ISSUE TITLE
[iOS] requestAuthentication

### ISSUE THREAD

**Issue by ital0** [pagseguromaster/plugpag#9]
Olá pessoal.

Estou criando um wrapper para React-Native da biblioteca PlugPag.
Acontece que, quando tento chamar o método requestAuthentication, estou recebendo o seguinte erro:

`e.reason	__NSCFString *	@"*** -[NSBundle initWithURL:]: nil URL argument"	0x00000001c2e721c0`

Abaixo segue o código:

```
RCT_EXPORT_METHOD(requestAuthentication:(NSDictionary *)request resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
{
    NSString *appName = [RCTConvert NSString:request[@"appName"]];
    NSString *appVersion = [RCTConvert NSString:request[@"appVersion"]];
    
    dispatch_sync(dispatch_get_main_queue(), ^{
        AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
        [[PlugPag sharedInstance] plugPagAppIdentification:appName withVersion:appVersion];
        @try {
            [[PlugPag sharedInstance] requestAuthentication:delegate.rootViewController];
        }
        @catch (NSException * e) {
            NSLog(@"Exception: %@", e);
        }
    });
}
```

Sobre minha UIViewController, ela já está exposta no AppDelegate.h e devidamente setada no AppDelegate.m, tanto que consigo utilizá-la com outras bibliotecas que também invocam um "modal de autenticação".
Conseguem visualizar o que está errado?

Obrigado!

**Comment by lucasmirandadev** [comment]
@ital0 eu já fiz um wrapper em react-native para o PlugPag, vou colocar open para a comunidade. Caso tenha uma dúvida posso te enviar a lib. abs

**Comment by ital0** [comment]
@lucasmirandadev opa Lucas, com certeza gostaria sim de ver a lib.
Pode me passar?

**Comment by hildequias** [comment]
@ital0 verifique se o arquivo PlugPag.bundle esta no seu projeto e passe como parametro delegate.window.rootViewController.
